name: Deploy

on:
  workflow_run:
    workflows: [Run Tests]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo Hi Toni