name: Deploy

on:
  workflow_run: 
    workflows: ["Run Tests"]
    types: 
      - completed
    push:
    branches:
      - main

jobs:
  deploy-on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The triggering workflow passed'
  # abort-on-failure:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event.workflow_run.conclusion == 'failure' }}
  #   steps:
  #     - run: echo 'The triggering workflow failed'