name: Run Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check tests
        run: pytest


name: Deploy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: run-pytest
    steps:
      - uses: actions/checkout@v3
      - run: echo Hi Toni