name: Run Test

on:
  push:
    branches:
      - main

  merge:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cehckout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: check lint
        run: flake8
      - name: Djano testing
        run: pytest
